---
- name: Make directory for packages
  file: path={{ remote_packages_dir }} state=directory

- name: Copy elliptics packages
  copy: src={{ item }} dest="{{ remote_packages_dir }}/"
  with_fileglob:
    - "{{ packages_dir }}/*"

- name: Inform apt about dependencies
  shell: >
    dpkg
    --force-depends
    --install
    --recursive
    {{ remote_packages_dir }}

- name: Satisfy packages dependencies
  shell: >
    apt-get
    --fix-broken
    --assume-yes
    install

- name: Install packages
  shell: >
    dpkg
    --install
    --recursive
    {{ remote_packages_dir }}
