{
    "type": "pytest",
    "target": "elliptics/recovery/merge",
    "addopts": "{% for node in servers %} --node={{ node.host }}:{{ node.port }}:{{ node.group }}{% endfor %} --file-size=10240 --consistent-files-number=256 --inconsistent-files-number=5000 --inconsistent-files-percentage=0.33 --cache-sync-timeout={{ cache_sync_timeout }} --backends-number={{ backends_number }} --recovery-timeout={{ recovery_timeout }}"
}
