---
- hosts: 127.0.0.1
  tasks:
    - name: Remove logs' directories
      local_action: file path={{ item }} state=absent
      with_items:
        - /tmp/logs
        - /tmp/logs-archive

    - name: Create logs' directories
      local_action: file path={{ item }} state=directory
      with_items:
        - /tmp/logs
        - /tmp/logs-archive

- hosts: servers
  tasks:
    - name: Copy servers logs
      fetch:
        src={{ elliptics_dir }}/{{ log_dir }}/elliptics.log
        dest=/tmp/logs/{{ ansible_hostname }}.log

- hosts: clients
  tasks:
    - name: Copy clients logs
      fetch:
        src={{ elliptics_dir }}/{{ log_dir }}/client.log
        dest=/tmp/logs/{{ ansible_hostname }}.log

- hosts: 127.0.0.1
  tasks:
    - name: zip files
      local_action: command zip /tmp/logs-archive/{{ item|replace("/tmp/logs/", "") }}.zip {{ item }}
      with_fileglob:
        - /tmp/logs/*
