---
- hosts: localhost
  tasks:
    - name: Remove test artifacts directories
      local_action: file path={{ artifacts_collecting_dir }} state=absent

    - name: Create test artifacts directories
      local_action: file path={{ artifacts_collecting_dir }} state=directory

- hosts: servers
  tasks:
    - name: Copy server logs
      fetch:
        src={{ log_file_path }}
        dest={{ artifacts_collecting_dir }}/{{ ansible_hostname }}.log
        flat=yes

    - name: Copy server configs
      fetch:
        src={{ config_file_path }}
        dest={{ artifacts_collecting_dir }}/{{ ansible_hostname }}.conf
        flat=yes

    - name: Create a file for backtraces
      file: dest={{ backtraces_dump_dir }} state=directory
      when: stop_nodes.get("failed", 0) == 1

    - name: Dump backtraces to a file
      shell: >
        gdb
        -ex "thread apply all bt"
        -batch
        -p {{ pidof.stdout }}
        >
        {{ backtraces_dump_file_path }}
      when: stop_nodes.get("failed", 0) == 1
      ignore_errors: yes

    - name: Copy dump file with backtraces
      fetch:
        src={{ backtraces_dump_file_path }}
        dest={{ artifacts_collecting_dir }}/{{ ansible_hostname }}.bt.dump
        flat=yes

- hosts: clients
  tasks:
    - name: Copy test logs
      synchronize:
        mode=pull
        src="{{ test_logs_path }}/*"
        dest="{{ artifacts_collecting_dir }}/{{ ansible_hostname }}-test-logs/"
      ignore_errors: yes

    - name: Copy recovery dc log
      fetch:
        src={{ recovery_dc_log_path }}
        dest={{ artifacts_collecting_dir }}/recovery_dc.log
        flat=yes
      ignore_errors: yes

    - name: Copy recovery merge log
      fetch:
        src={{ recovery_merge_log_path }}
        dest={{ artifacts_collecting_dir }}/recovery_merge.log
        flat=yes
      ignore_errors: yes

- hosts: localhost
  vars:
    test_name: '{{ inventory_file.split(".")[0].rsplit("/", 1)[-1] }}'
  tasks:
    - name: zip files
      shell: >
        cd {{ artifacts_collecting_dir }};
        zip -r {{ artifacts_dir }}/test-{{ test_name }}.zip ./;
