---
- hosts: elliptics-test
  roles:
    - host-preparation

    - {role: elliptics-install-packages, when: packages_dir is defined}

    - {role: elliptics-common, when: packages_dir is not defined}

- hosts: elliptics-client
  roles:
    - elliptics-pytest
