---
- hosts: servers
  tasks:
    - name: Getting process id
      shell: pgrep dnet_ioserv
      register: pgrep

    - name: Stop Elliptics daemon
      shell: pkill dnet_ioserv

    - name: Wait for Elliptics to stop
      shell: while [ -e /proc/{{ pgrep.stdout }} ]; do sleep 0.1; done
      async: 600
      poll: 15
