---
- hosts: all
  sudo: yes
  tasks:
    - name: Perform 'apt-get update'
      apt: update_cache=yes
      register: apt_update
      ignore_errors: yes

- hosts: all
  gather_facts: no
  sudo: yes
  roles:
    - {role: apt-update-fix, when: apt_update|failed}

- hosts: all
  sudo: yes
  roles:
    - {role: install-elliptics-from-debs, when: packages_dir is defined}

    - {role: install-elliptics-from-repo, when: packages_dir is not defined}

- hosts: servers
  sudo: yes
  tasks:
    - name: Create logging directories
      file: path={{ elliptics_dir }}/{{ log_dir }} state=directory

    - name: Create data and history directories
      file: path={{ elliptics_dir }}/{{ item[0] }}/{{ item[1] }} state=directory
      with_nested:
        - "[{% for i in range(backends_number) %} {{ i }} {% if not loop.last %},{% endif %} {% endfor %}]"
        - ["{{ data_dir }}", "{{ hist_dir }}"]

    - name: Create data file
      file: path={{ elliptics_dir }}/{{ item }}/{{ data_dir }}/data state=touch
      with_items:
        - "[{% for i in range(backends_number) %} {{ i }} {% if not loop.last %},{% endif %} {% endfor %}]"
