---
- hosts: all
  tasks:
    - name: Perform 'apt-get update'
      apt: update_cache=yes
      register: apt_update
      ignore_errors: yes

- hosts: all
  gather_facts: no
  roles:
    - {role: apt-update-fix, when: apt_update|failed}

- hosts: all
  roles:
    - {role: install-elliptics-from-debs, when: packages_dir is defined}

    - {role: install-elliptics-from-repo, when: packages_dir is not defined}

- hosts: servers
  tasks:
    - name: Create necessary directories
      file: path={{ item }} state=directory
      with_items:
        - "{{ log_dir }}"
        - "{{ data_dir }}"
        - "{{ hist_dir }}"

    - name: Create data file
      file: path={{ data_dir }}/data state=touch
