---
- hosts: all
  tasks:
    - name: Set hostname
      shell: echo "127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname_short }} localhost" > /etc/hosts; hostname {{ inventory_hostname_short }}

    # to prevent "Hash sum mismatch" error
    - name: Clean up apt/lists/
      shell: rm -rf /var/lib/apt/lists/*

    - name: Perform 'apt-get update'
      apt: update_cache=yes

- hosts: all
  roles:
    - {role: install-elliptics-from-debs, when: packages_dir is defined}

    - {role: install-elliptics-from-repo, when: packages_dir is not defined}

- hosts: servers
  tasks:
    - name: Create necessary directories
      file: path={{ item }} state=directory
      with_items:
        - "{{ log_dir }}"
        - "{{ data_dir }}"
        - "{{ hist_dir }}"

    - name: Create data file
      file: path={{ data_dir }}/data state=touch
