---
- include: install-elliptics.yml

- hosts: clients
  tasks:
    - name: Install debian packages
      apt: pkg={{ item }}
      with_items:
        - python-pip
        - wondershaper

    - name: Install Python packages
      pip: name={{ item }} use_mirrors=no
      with_items:
        - pytest
        - pytest-xdist
        - pyhamcrest
        - requests

    - name: Copy test files
      copy: src={{ repo_dir }}/tests dest={{ remote_repo_dir }}

    - name: Copy lib files
      copy: src={{ repo_dir }}/lib dest={{ remote_repo_dir }}
