---
- include: install-elliptics.yml

- hosts: servers
  sudo: yes
  tasks:
    - name: Install gdb
      apt: pkg=gdb

- hosts: clients
  sudo: yes
  tasks:
    - name: Install debian packages
      apt: pkg={{ item }}
      with_items:
        - python-pip
        - wondershaper

    - name: Install Python packages
      pip: name={{ item }}
      register: result
      until: result|success
      retries: 3
      delay: 10
      with_items:
        - setuptools
        - pytest
        - pytest-xdist
        - pytest-timeout
        - pyhamcrest
        - requests

- hosts: localhost
  tasks:
    - name: Remove test suite artifacts directory
      local_action: file path={{ artifacts_dir }} state=absent

    - name: Create test suite artifacts directory
      local_action: file path={{ artifacts_dir }} state=directory
