---
- name: Install cocaine-tools
  apt: pkg={{ item }}
  with_items:
    - cocaine-tools={{ cocaine_tools_version }}
    - cocaine-framework-python={{ cocaine_framework_python_version }}

- name: Install aptitude and pbuilder
  apt: pkg={{ item }}
  with_items:
    - pbuilder
    - aptitude

- name: Clone Grape sources from git
  git: repo=https://github.com/reverbrain/grape.git
       dest={{ grape_src }}
       version={{ grape_version }}

- name: Install build dependencies
  shell: sudo /usr/lib/pbuilder/pbuilder-satisfydepends --control {{ grape_src }}/debian/control

- name: Install packages with custom versions
  apt: pkg=elliptics-dev={{ elliptics_version }},libcocaine-core2={{ libcocaine_version }},libcocaine-dev={{ libcocaine_version }},cocaine-framework-native={{ cocaine_framework_native_version }},cocaine-framework-native-dev={{ cocaine_framework_native_version }} force=yes

- name: Build Grape
  shell: cd {{ grape_src }}; debuild -uc -us -tc -i -I

- name: Copy built Grape packages onto nodes
  shell: "scp /tmp/grape*deb {{ item }}:"
  with_items: groups.servers
