---
- name: Create logging directories
  file: path={{ log_dir }} state=directory

- name: Create data and history directories
  file: path={{ item[0] }}/{{ item[1] }} state=directory
  with_nested:
    - ["{{ data_dir }}", "{{ hist_dir }}"]
    - >
        [{% for i in range(backends_number) %}
          {{ i }} {% if not loop.last %},{% endif %}
        {% endfor %}]

- name: Create data file
  file: path={{ data_dir }}/{{ item }}/data state=touch
  with_items:
    - >
        [{% for i in range(backends_number) %}
          {{ i }} {% if not loop.last %},{% endif %}
        {% endfor %}]
